import type { WardrobeItem } from "./types";

/** Small deterministic wardrobe for docs/tests — hex-first, no name reliance. */
export const SAMPLE_WARDROBE_ITEMS: WardrobeItem[] = [
  {
    id: "s-top-1",
    title: "White Oxford",
    category: "top",
    colorHex: "#f5f0e8",
    colorName: "off_white",
    pattern: "solid",
    formality: "smart_casual",
    status: "clean",
  },
  {
    id: "s-top-2",
    title: "Navy Tee",
    category: "top",
    colorHex: "#1a2942",
    colorName: "navy",
    pattern: "solid",
    formality: "casual",
    status: "clean",
  },
  {
    id: "s-bot-1",
    title: "Beige Chinos",
    category: "bottom",
    colorHex: "#c4a882",
    colorName: "beige",
    pattern: "solid",
    formality: "smart_casual",
    status: "clean",
  },
  {
    id: "s-bot-2",
    title: "Black Jeans",
    category: "bottom",
    colorHex: "#1a1a1a",
    colorName: "black",
    pattern: "solid",
    formality: "casual",
    status: "clean",
  },
  {
    id: "s-shoe-1",
    title: "Brown Loafers",
    category: "footwear",
    colorHex: "#5c4033",
    colorName: "brown",
    pattern: "solid",
    formality: "smart_casual",
    status: "clean",
  },
  {
    id: "s-shoe-2",
    title: "White Sneakers",
    category: "footwear",
    colorHex: "#eeeeee",
    colorName: "white",
    pattern: "solid",
    formality: "casual",
    status: "clean",
  },
  {
    id: "s-layer-1",
    title: "Olive Overshirt",
    category: "layer",
    colorHex: "#4b5320",
    colorName: "olive",
    pattern: "solid",
    formality: "casual",
    status: "clean",
  },
];
